import React from "react";
import Header from "@/components/Header";
import ChazaStore from "@/components/Client/ChazaStore";
import {Chaza} from "@/types/chaza";
import {Product} from "@/types/product"

const products:Product[] = [
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Esto es una bebida",
    price: "$2.800",
    category: "Bebidas",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Esto es una bebida",
    price: "$2.800",
    category: "Bebidas",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Esto es una bebida",
    price: "$2.800",
    category: "Bebidas",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Bebidas",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Esto es una bebida",
    price: "$2.800",
    category: "Bebidas",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Esto es una bebida",
    price: "$2.800",
    category: "Bebidas",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Esto es una bebida",
    price: "$2.800",
    category: "Bebidas",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Bebidas",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
  {
    name: "Empanada de pollo y champiñon",
    description: "Empanada rellena de pollo desmechado, arroz y champiñones.",
    price: "$2.800",
    category: "Comida rapida",
    image: "/images/empanada.png",
    stock: 10,
    total_sales: 0,
  },
];

const chaza:Chaza={
  _id: "_ID",
  owner: "John Silva",
  name: "Chaza de John",
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  type: 1,
  address: "Frente al FEM",
  phone: "3138946439",
  products: products,
  score: 100,
  image: "https://example.png",
  payment_method: [
    0,
    0,
    0,
  ],
}

function chazaStore(/*{chaza}: {chaza:Chaza}*/) {
  return (
    <>
      <Header></Header>
      <ChazaStore chaza={chaza}></ChazaStore>
    </>
  );
}

export default chazaStore;